name: CLA Assistant

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        uses: contributor-assistant/github-action@v2.5.0
        with:
          path-to-signatures: 'cla-signatures.json'
          path-to-document: 'https://github.com/bniladridas/calculator/blob/main/CLA.md'
          branch: 'main'
          allowlist: 'dependabot[bot],github-actions[bot]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}